### ISSUE TITLE
Mapping weights to configs

### ISSUE THREAD

**Issue by YoushaaMurhij** [OPEN-AIR-SUN/SISC#1]
Nice work! I've tried to run your method with the provided pretrained models but I got errors about mismatching between the model and the loaded weights.
Can you please provide a sample config files for some of your pretrained models?

Thanks!

```bash
Traceback (most recent call last):
  File "main_sc.py", line 670, in <module>
    main()
  File "main_sc.py", line 666, in main
    visualize(opt, config, expr_path)
  File "main_sc.py", line 595, in visualize
    G_model.module.load_state_dict(checkpoint['G_model'])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for G_siren:
	Missing key(s) in state_dict: "G_model.net.net.0.0.weight", "G_model.net.net.0.0.bias", "G_model.net.net.1.0.weight", "G_model.net.net.1.0.bias", "G_model.net.net.2.0.weight", "G_model.net.net.2.0.bias", "G_model.net.net.3.0.weight", "G_model.net.net.3.0.bias", "G_model.net.net.4.0.weight", "G_model.net.net.4.0.bias". 
	Unexpected key(s) in state_dict: "net.net.0.0.weight", "net.net.0.0.bias", "net.net.1.0.weight", "net.net.1.0.bias", "net.net.2.0.weight", "net.net.2.0.bias", "net.net.3.0.weight", "net.net.3.0.bias", "net.net.4.0.weight", "net.net.4.0.bias". 
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 467) of binary: /usr/bin/python3



```

**Comment by Philipflyg** [comment]
> 

Thanks for your attention! I've modified the codes and provided the corresponding config files.   : )
